# Generated by Django 5.1.6 on 2025-02-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.TextField(default='No context provided'),
            preserve_default=False,
        ),
    ]
