# Generated by Django 5.1.6 on 2025-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_question_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
