# Generated by Django 5.1.6 on 2025-05-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('question_app', '0003_question_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='conversation.conversation'),
            preserve_default=False,
        ),
    ]
