name: Run Tests on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ensure pip cache directory exists
        run: mkdir -p %USERPROFILE%\.cache\pip
        shell: cmd

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: %USERPROFILE%\.cache\pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install your package in editable mode
        run: pip install -e .
        timeout-minutes: 10

      - name: Save dependencies cache
        uses: actions/cache@v3
        with:
          path: %USERPROFILE%\.cache\pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Run tests
        env:
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
          TOKEN: ${{ secrets.TOKEN }}
        run: pytest
